development:
  adapter: postgresql
  database: bath_living_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bath_living_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bath_living
  pool: 5
  timeout: 5000
