defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  database: bath_living_dev
  <<: *defaults

test:
  database: bath_living_test
  <<: *defaults

production:
  database: bath_living
  <<: *defaults
